name: Publish

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Delete huge unnecessary tools folder
        run: rm -rf /opt/hostedtoolcache

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(git describe --tags --always)

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: mos4ic
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            mos4ic/communex-api:${{ steps.get_version.outputs.VERSION }}
            mos4ic/communex-api:latest

  deploy:
    needs: docker
    runs-on: self-hosted
    steps:
      - name: Update production container
        run: cd ../comex-api && docker compose pull && docker compose up -d
